builds:
  - main: ./cmd/helmecr
    binary: ./bin/helmecr
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
