name: "ecr"
version: "v0.1.4"
usage: "Install Helm charts hosted on Amazon ECR"
description: |-
  Helm plugin that supports installing Charts from AWS ECR.
command: "$HELM_PLUGIN_DIR/bin/helmecr"
downloaders:
- command: "bin/helmecr"
  protocols:
    - "ecr"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./hack/install.sh"
